In [1]:
import pandas as pd

In [2]:
df= pd.read_csv("/content/train 2.csv")

In [3]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [4]:
df.isnull().sum()

id           0
title      558
author    1957
text        39
label        0
dtype: int64

In [7]:
df.shape

(20800, 5)

In [8]:
df.info

<bound method DataFrame.info of           id                                              title  \
0          0  House Dem Aide: We Didn’t Even See Comey’s Let...   
1          1  FLYNN: Hillary Clinton, Big Woman on Campus - ...   
2          2                  Why the Truth Might Get You Fired   
3          3  15 Civilians Killed In Single US Airstrike Hav...   
4          4  Iranian woman jailed for fictional unpublished...   
...      ...                                                ...   
20795  20795  Rapper T.I.: Trump a ’Poster Child For White S...   
20796  20796  N.F.L. Playoffs: Schedule, Matchups and Odds -...   
20797  20797  Macy’s Is Said to Receive Takeover Approach by...   
20798  20798  NATO, Russia To Hold Parallel Exercises In Bal...   
20799  20799                          What Keeps the F-35 Alive   

                                          author  \
0                                  Darrell Lucus   
1                                Daniel J. Flynn   
2      

In [12]:
df=df.dropna()

In [13]:
df.isnull().sum()

id        0
title     0
author    0
text      0
label     0
dtype: int64

In [18]:
X=df.drop('label', axis=1)

In [19]:
X.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  
0  House Dem Aide: We Didn’t Even See Comey’s Let...  
1  Ever get the feeling your life circles the rou...  
2  Why the Truth Might Get You Fired October 29, ...  
3  Videos 15 Civilians Killed In Single US Airstr...  
4  Print \nAn Iranian woman has been sentenced to...

In [20]:
y= df['label']

In [21]:
y.head()

0    1
1    0
2    1
3    1
4    1
Name: label, dtype: int64

In [22]:
y.value_counts()

0    10361
1     7924
Name: label, dtype: int64

In [23]:
X.shape

(18285, 4)

In [24]:
y.shape

(18285,)

In [25]:
import tensorflow as tf

In [26]:
tf.__version__

'2.15.0'

In [27]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [29]:
vocab_size=7000

In [30]:
msgs= X.copy()

In [32]:
msgs.reset_index(inplace=True)

In [33]:
import nltk
import re
from nltk.corpus import stopwords

In [34]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [36]:
msgs['title'][0]

'House Dem Aide: We Didn’t Even See Comey’s Letter Until Jason Chaffetz Tweeted It'

In [41]:
from nltk.stem.porter import PorterStemmer
ps= PorterStemmer()
corpus=[]

for i in range (0, len(msgs)):
  review= re.sub('[^a-zA-Z]',' ',msgs['title'][i])
  review= review.lower()
  review= review.split()
  review= [ps.stem(word) for word in review if not word in stopwords.words('english')]
  review= ' '.join(review)
  corpus.append(review)

In [42]:
corpus

['hous dem aid even see comey letter jason chaffetz tweet',
 'flynn hillari clinton big woman campu breitbart',
 'truth might get fire',
 'civilian kill singl us airstrik identifi',
 'iranian woman jail fiction unpublish stori woman stone death adulteri',
 'jacki mason hollywood would love trump bomb north korea lack tran bathroom exclus video breitbart',
 'beno hamon win french socialist parti presidenti nomin new york time',
 'back channel plan ukrain russia courtesi trump associ new york time',
 'obama organ action partner soro link indivis disrupt trump agenda',
 'bbc comedi sketch real housew isi caus outrag',
 'russian research discov secret nazi militari base treasur hunter arctic photo',
 'us offici see link trump russia',
 'ye paid govern troll social media blog forum websit',
 'major leagu soccer argentin find home success new york time',
 'well fargo chief abruptli step new york time',
 'anonym donor pay million releas everyon arrest dakota access pipelin',
 'fbi close hilla

In [43]:
onehot_repr= [one_hot(words,vocab_size) for words in corpus]

In [44]:
onehot_repr

[[5175, 4583, 2828, 5071, 5329, 2953, 1224, 2308, 2631, 2065],
 [4363, 977, 6785, 4639, 6327, 6617, 1562],
 [4501, 6780, 891, 5550],
 [3469, 1046, 2759, 2644, 6359, 970],
 [5071, 6327, 5392, 3157, 6687, 5489, 6327, 5473, 5039, 5999],
 [2317,
  5336,
  4634,
  5060,
  4261,
  1634,
  1619,
  4658,
  4718,
  2542,
  404,
  2792,
  2842,
  4791,
  1562],
 [6679, 2387, 526, 1274, 4874, 3514, 1701, 2869, 5199, 5324, 1685],
 [3009, 5921, 5423, 4237, 2570, 2044, 1634, 1366, 5199, 5324, 1685],
 [613, 6649, 3732, 6087, 2238, 6110, 2070, 5092, 1634, 4713],
 [1518, 6566, 5105, 4932, 5080, 2080, 2012, 2912],
 [4704, 2632, 3078, 4750, 790, 5882, 1356, 5184, 5559, 942, 1569],
 [2644, 823, 5329, 6110, 1634, 2570],
 [132, 6339, 4265, 3676, 1253, 6271, 721, 3692, 5054],
 [4349, 5478, 5814, 4016, 3562, 5095, 352, 5199, 5324, 1685],
 [966, 359, 4572, 4683, 3005, 5199, 5324, 1685],
 [4222, 1526, 1390, 6158, 4511, 1623, 1871, 3803, 6135, 1342],
 [6976, 6774, 977],
 [3114, 1135, 5304, 114, 1634, 6597, 1271,

In [45]:
sen_len= 25
embeds= pad_sequences(onehot_repr, padding='pre', maxlen= sen_len)
embeds

array([[   0,    0,    0, ..., 2308, 2631, 2065],
       [   0,    0,    0, ..., 6327, 6617, 1562],
       [   0,    0,    0, ..., 6780,  891, 5550],
       ...,
       [   0,    0,    0, ..., 5199, 5324, 1685],
       [   0,    0,    0, ..., 4719,  996, 4637],
       [   0,    0,    0, ...,  789, 1463, 3481]], dtype=int32)

In [46]:
len(embeds)

18285

In [47]:
embed_vec_features=50
model= Sequential()
model.add(Embedding(vocab_size,embed_vec_features,input_length=sen_len))
model.add(LSTM(100))
model.add(Dense(1, activation= 'sigmoid'))
model.compile(loss='binary_crossentropy', optimizer= 'adam', metrics=['accuracy'])
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 25, 50)            350000    
                                                                 
 lstm (LSTM)                 (None, 100)               60400     
                                                                 
 dense (Dense)               (None, 1)                 101       
                                                                 
Total params: 410501 (1.57 MB)
Trainable params: 410501 (1.57 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
len(embeds)

18285

In [49]:
y.shape

(18285,)

In [52]:
import numpy as np
X_final= np.array(embeds)
y_final= np.array(y)

In [54]:
X_final.shape

(18285, 25)

In [55]:
y_final.shape

(18285,)

In [56]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test= train_test_split(X_final, y_final, test_size= 0.25, random_state= 42)

In [58]:
model.fit(X_train, y_train, validation_data= (X_test, y_test), epochs= 10, batch_size= 64)

Epoch 1/10
215/215 [==============================] - 13s 49ms/step - loss: 0.3088 - accuracy: 0.8563 - val_loss: 0.2131 - val_accuracy: 0.9116
Epoch 2/10
215/215 [==============================] - 11s 50ms/step - loss: 0.1245 - accuracy: 0.9517 - val_loss: 0.2079 - val_accuracy: 0.9197
Epoch 3/10
215/215 [==============================] - 8s 39ms/step - loss: 0.0825 - accuracy: 0.9717 - val_loss: 0.2063 - val_accuracy: 0.9167
Epoch 4/10
215/215 [==============================] - 11s 51ms/step - loss: 0.0571 - accuracy: 0.9816 - val_loss: 0.2586 - val_accuracy: 0.9151
Epoch 5/10
215/215 [==============================] - 10s 47ms/step - loss: 0.0377 - accuracy: 0.9875 - val_loss: 0.3888 - val_accuracy: 0.9164
Epoch 6/10
215/215 [==============================] - 12s 56ms/step - loss: 0.0226 - accuracy: 0.9934 - val_loss: 0.4461 - val_accuracy: 0.9068
Epoch 7/10
215/215 [==============================] - 8s 39ms/step - loss: 0.0190 - accuracy: 0.9944 - val_loss: 0.3824 - val_accuracy: 0

In [71]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

143/143 [==============================] - 1s 9ms/step


In [72]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2396,  204],
       [ 215, 1757]])

In [75]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9083552055993

In [77]:
from tensorflow.keras.layers import Dropout
## Creating model
embedding_vector_features=40
model=Sequential()
model.add(Embedding(vocab_size,embed_vec_features,input_length=sen_len))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [78]:
model.fit(X_train, y_train, validation_data= (X_test, y_test), epochs= 10, batch_size= 64)

Epoch 1/10
215/215 [==============================] - 14s 43ms/step - loss: 0.3197 - accuracy: 0.8577 - val_loss: 0.2022 - val_accuracy: 0.9132
Epoch 2/10
215/215 [==============================] - 10s 48ms/step - loss: 0.1310 - accuracy: 0.9503 - val_loss: 0.2028 - val_accuracy: 0.9125
Epoch 3/10
215/215 [==============================] - 11s 50ms/step - loss: 0.0917 - accuracy: 0.9669 - val_loss: 0.2269 - val_accuracy: 0.9186
Epoch 4/10
215/215 [==============================] - 10s 47ms/step - loss: 0.0679 - accuracy: 0.9769 - val_loss: 0.2421 - val_accuracy: 0.9169
Epoch 5/10
215/215 [==============================] - 9s 40ms/step - loss: 0.0453 - accuracy: 0.9843 - val_loss: 0.2728 - val_accuracy: 0.9127
Epoch 6/10
215/215 [==============================] - 11s 50ms/step - loss: 0.0292 - accuracy: 0.9908 - val_loss: 0.3367 - val_accuracy: 0.9116
Epoch 7/10
215/215 [==============================] - 13s 60ms/step - loss: 0.0219 - accuracy: 0.9936 - val_loss: 0.4509 - val_accuracy: 

In [79]:
y_pred = (model.predict(X_test) > 0.5).astype("int32")

143/143 [==============================] - 2s 10ms/step


In [80]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test,y_pred)

array([[2366,  234],
       [ 157, 1815]])

In [81]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9144794400699913

In [82]:
X_test= pd.read_csv('/content/predictions.csv')

In [83]:
X_test.head()

0  1  2  3  4  5  6  7  8  9  ...    15    16    17    18    19    20  \
0  0  0  0  0  0  0  0  0  0  0  ...   522  5360  3656   283  1501   901   
1  0  0  0  0  0  0  0  0  0  0  ...  6910  4739  6285   402  3168  4943   
2  0  0  0  0  0  0  0  0  0  0  ...  2501  2934  4620  4456  4288  6576   
3  0  0  0  0  0  0  0  0  0  0  ...     0     0     0     0     0  3650   
4  0  0  0  0  0  0  0  0  0  0  ...     0  5982   317  2091  2700  2947   

     21    22    23    24  
0  4671  2006  2957  6576  
1  3119  4927  3154  1014  
2   705  2006  2957  6576  
3  4776  5970  4272  2173  
4  3597  1597   522  2268  

[5 rows x 25 columns]

In [84]:
test_val = (model.predict(X_test) > 0.5).astype("int32")

143/143 [==============================] - 2s 9ms/step


In [85]:
test_val

array([[0],
       [0],
       [0],
       ...,
       [1],
       [0],
       [0]], dtype=int32)

In [87]:
df = pd.DataFrame(test_val)
df.to_csv('Submit_final.csv', index=False)